# This is a basic workflow to gather the files that have been newly created/edited.

name: get-changed-files

# When markdown files are pushed to the main branch.
on:
 push:
  paths:
    - '**.md'
  branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
